# Generated by Django 5.2 on 2025-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
