# Generated by Django 5.2 on 2025-05-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='team',
            new_name='teamName',
        ),
    ]
