# Generated by Django 5.2 on 2025-05-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_team_message_teamname'),
        ('teams', '0002_teammemberrequest_rejected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='teamName',
        ),
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teams.team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
