# Generated by Django 5.2 on 2025-04-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
