# Generated by Django 5.2 on 2025-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordrow',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
