# Generated by Django 5.2.1 on 2025-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_recordrow_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
