# Generated by Django 5.2.1 on 2025-06-01 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammemberrequest_rejected_at'),
        ('todo', '0005_alter_subtask_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrow',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
    ]
