# Generated by Django 5.2.1 on 2025-06-01 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigntask', '0001_initial'),
        ('teams', '0002_teammemberrequest_rejected_at'),
        ('todo', '0006_recordrow_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordRow',
            new_name='Task',
        ),
    ]
