# Generated by Django 5.2 on 2025-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
