# Generated by Django 5.2.1 on 2025-05-25 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0004_alter_recordrow_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage (0–100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.subtask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.recordrow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
